/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#00dce5",
        "on-tertiary": "#611200",
        "on-secondary-container": "#0f6d00",
        "tertiary-fixed-dim": "#ffb4a2",
        "surface-container": "#1e2024",
        "surface-bg": "#111317",
        "inverse-primary": "#00696e",
        "tertiary-container": "#ffd4ca",
        "on-secondary-fixed-variant": "#095300",
        "on-secondary": "#053900",
        "on-tertiary-fixed": "#3c0700",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#891d00",
        "primary-fixed-dim": "#00dce5",
        "on-background": "#e2e2e8",
        "surface-container-highest": "#333539",
        "secondary": "#d7ffc5",
        "inverse-surface": "#e2e2e8",
        "secondary-container": "#2ff801",
        "on-secondary-fixed": "#022100",
        "surface-variant": "#333539",
        "surface-bright": "#37393e",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#006c71",
        "on-error": "#690005",
        "surface-container-low": "#1a1c20",
        "primary-fixed": "#63f7ff",
        "surface-color": "#111317",
        "on-surface": "#e2e2e8",
        "surface-dim": "#111317",
        "surface-container-lowest": "#0c0e12",
        "secondary-fixed-dim": "#2ae500",
        "on-primary-fixed": "#002021",
        "on-primary-fixed-variant": "#004f53",
        "error": "#ffb4ab",
        "outline": "#849495",
        "surface-container-high": "#282a2e",
        "primary-container": "#00f5ff",
        "outline-variant": "#3a494a",
        "tertiary-fixed": "#ffdad2",
        "inverse-on-surface": "#2f3035",
        "tertiary": "#fff9f7",
        "on-primary": "#003739",
        "secondary-fixed": "#79ff5b",
        "on-surface-variant": "#b9caca",
        "primary": "#e9feff",
        "on-tertiary-container": "#b92a00",
        "surface-fg": "#111317",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
        mono: ["Geist", "monospace"],
      },
      spacing: {
        " gutters": "12px",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
      },
    },
  },
  plugins: [],
};
